#!/usr/bin/env bun
/**
 * Reads version from package.json and writes src/version.ts
 */
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const pkg = await Bun.file(resolve(root, "package.json")).json();
const content = `// Auto-generated by scripts/version.ts — do not edit\nexport const VERSION = '${pkg.version}';\n`;

await Bun.write(resolve(root, "src/version.ts"), content);
console.log(`Wrote src/version.ts with version ${pkg.version}`);
